### PR TITLE
Prtkgpt

### PR DESCRIPTION
**Pull request by prtkgpt**

### CODE REVIEW

**Comment by durden** [comment]
Do you want me to merge this?  I'll probably do it manually because your branch has a lot of old changes from testing all the way back to Nov 24th.  I think the only essential changes are to 'Building a Dashboard in React' and 'Tips and cool tricks to use in git'.  Is that right?

The weird thing is the diff of both articles looks like every line changed.  Maybe just the newlines changed?

**Comment by prtkgpt** [comment]
just the last two (dashboard + tip n tricks)

**Comment by durden** [comment]
Cool.  I'll merge them manually and delete your branch.  Then, it'll get automatically created when you edit another article.  Then, the merges should be easier to do via github.com since you won't have commits so far behind the master branch.

**Comment by durden** [comment]
Ok, manually merged these changes.  See the following commits for details:
- [Changes to git tips guide](https://github.com/pluralsight/guides/commit/bafc98128e3f69b89f2e9e0973e8cccfa2eaed68)
- [Changes to React dashboard guide](https://github.com/pluralsight/guides/commit/58f76894765fd1ffda23c83949f0977013185939)

Let me know if something isn't right.  I'll delete your branch and you can hit the edit button on these guides from the hack.guides() site again and your changes should merge much more cleanly.

**Pull request closed without merging**
