### PR TITLE
Updates to "Tips and cool tricks to use in git"

### PR DESCRIPTION
**Pull request by serbiant**
Hello there,
I am using stashes very often and I have quite specific projects - there are lots of generated files with the same names could be created by me or by another developer. To avoid any inconvenience at this point and be very confident about no-conflicts when pulling code, and keep an eye on untracked files, I use `git stash -u`, which also stashes untracked files. Hopefully not only myself considers it handy.

### CODE REVIEW

**Comment by durden** [comment]
Thanks for the suggestions @serbiant .  Any thoughts on incorporating these suggestions @andreybleme?  I can merge them for you or feel free to respond here with other suggestions.  Let me know if I can help!

**Comment by serbiant** [comment]
@durden Thanks for the response! I guess @andreybleme 's reaction below my comment says by himself. :)

**Comment by andreybleme** [comment]
@serbiant Yes man. @durden can you merge it?

BTW, thanks for improving the guide @serbiant! :100:

**Comment by durden** [comment]
Thanks @andreybleme for the response.  Everything is merged now!

**Comment by serbiant** [comment]
@andreybleme always welcome! By the way I got inspired by you guys and half way through my own article. :)

**Pull request merged**
