### PR TITLE
Updates to "Getting the consolidated sum of transactions grouped by c…

### PR DESCRIPTION
**Pull request by adityavarshney**
…urrency just using MySQL"

### CODE REVIEW

**Comment by durden** [comment]
@praveenscience Would you like me to merge these changes?  You're welcome to merge them yourself manually or let me know if you want me to reject them and close the PR.  Thanks for your contribution!

**Comment by praveenscience** [comment]
I don't have merge access. Can someone add me as a collaborator? @durden.

Also @adityavarshney There are lot of mistakes in this.

`Transactio` - n missing:

image

Double spacing:

image

`mmakes` instead of `makes`?

image

I am not sure if this is still in draft. Can you please confirm if this is the final with the mistakes?

**Comment by durden** [comment]
@adityavarshney Can you make these changes?  The PR will automatically update after you push your changes to your branch.  Thanks for reviewing @praveenscience!

**Comment by praveenscience** [comment]
Excellent... I am waiting for a collaborator access from @prtkgpt... 😃

**Comment by adityavarshney** [comment]
Committed revisions. Fixed mistakes above and some other copy errors. @praveenscience thanks for spotting the problems.

**Comment by prtkgpt** [comment]
thanks guys, I just merged the pull request.

**Comment by praveenscience** [comment]
Yay! 😄

**Pull request merged**
