### PR TITLE
Eh3rrera microsoft net building a generic csv writer reader using reflection

### PR DESCRIPTION
**Pull request by eh3rrera**
Typo and grammar fixes and some formatting changes.

### CODE REVIEW

**Comment by durden** [comment]
@eh3rrera appreciate the help editing!  What do you think about these edits @aykanatm ?

**Comment by aykanatm** [comment]
I think they are good. Thanks!

**Comment by eh3rrera** [comment]
Thanks for you guide @aykanatm :+1:

**Comment by durden** [comment]
All merged, thanks again guys!!

**Comment by eh3rrera** [comment]
Thanks @durden!

**Pull request merged**
