### PR TITLE
polymer draft :)

### PR DESCRIPTION
**Pull request by brown2rl**
@prtkgpt, were you wanting to create a branch for each episode in the series?  i made sub directories for them currently, and put them in the `"branches":[]"` field.

### CODE REVIEW

**Comment by durden** [comment]
Thanks for the proposed series! The only issue with this PR is the usage of the `branches` field.  The `branches` metadata is meant to hold the list of github branches that others have created to suggest article edits.

Another approach might be to create several files in the main article directory alongside the main article.md.  Then, our editors can edit them separately and we'll have the git history during the process.  This way you'll get github contribution credit for all your changes along the way.  Then, we'll copy all the files into the main article.md for publishing 1 guide.

@prtkgpt What are your suggestions? Maybe we could the route above or did you want to publish each episode in the series as a new guide?

**Comment by brown2rl** [comment]
@durden thanks for the clarification!  is there a way to suggest a direction of suggested edits?  maybe allow something like the following:

```
branches: [
          {series1: ['git-url-branch-1','git-url-branch-2']}, 
          {series2: ['git-url-branch-1','git-url-branch-2']}
]
```

i was thinking about the other approach, as well.

**Comment by durden** [comment]
@brown2rl Sorry, there isn't a way to suggest a direction of edits right now.  The branches field is exclusively for edits to a single article, not a series.  The reason for this is the metadata file only pertains to a single guide, not a series.  We might want to implement a feature in the future to track a list of guides and aggregate them into a series.  However, I don't expect that to be added for a while.

The best approach now is to write a new guide for each new entry in the series.  We can always combine them at the end to publish 1 comprehensive guide.  However, I'll leave it up to @prtkgpt whether to publish the guides separately or all in 1 guide.

**Comment by brown2rl** [comment]
@durden thanks again!

**Comment by durden** [comment]
@brown2rl Anytime!  I'm going to go ahead and merge this then edit cleanup the branches usage.  Your guide should show up as a draft on your profile page on the hack.guides() site.  You can continue editing there or update your local checkout of this repo and submit another PR.

**Comment by durden** [comment]
Another thing I forgot to mention is the folder for the guide needs to match the title from `details.json`, with all 'special' characters changed to `-`.  Just a design quirk right now.  You can see your guide at the following locations now:
- Your [profile page](http://pluralsight.com/guides/author/brown2rl)
- [This direct link to hack guides](http://pluralsight.com/guides/front-end-javascript/polymer-user-interfaces-for-the-next-evolution-of-the-web?status=draft)
- [This folder on github](https://github.com/pluralsight/guides/tree/master/draft/front-end-javascript/polymer-user-interfaces-for-the-next-evolution-of-the-web)

Thanks for the submission.  Looking forward to seeing it all come together!

**Pull request merged**
