### PR TITLE
Naba sadia siddiqui

### PR DESCRIPTION
**Pull request by NabaSadiaSiddiqui**
Fixed a typo, and added a term here and there to make the context clearer

### CODE REVIEW

**Comment by durden** [comment]
Thanks for the editing @NabaSadiaSiddiqui. @scharf Any thoughts on incorporating these additions into your guide?  @scharf You can let me know in this thread if you want me to merge any of these edits.  There are a few options for how to proceed:
1. You can manually make them in your guide on the [hack.guides()](http://www.pluralsight.com/guides/) website.
2. Add comments on the [commit lines](https://github.com/pluralsight/guides/pull/38/commits/fa4cb66365785417d680d9db0493d1f2acb9628f) itself to indicate which changes you do and do not want.  Then, @prtkgpt or I will merge them for you.

Thanks everyone for a cool guide.  My Java is **very** rusty and reading through this guide was fun.

**Comment by scharf** [comment]
All the changes look good -- it seems something went wrong with the whitespace, which causes all the text to show up as changed.

**Comment by scharf** [comment]
ah now I realize -- the entire paragraphs are single lines that causes the entire paragraph to change if a single word changes....

**Comment by durden** [comment]
Good point. I'll look into seeing if we can improve the diff'ing and not show an entire paragraph changes. Probably depends on if there are line breaks in the original text, but it's worth a look!

**Comment by scharf** [comment]
I think the lines are really long in my original text -- when I write `.md` files directly, I use a line length of 80 chars or so, but in this case I did not think about that...

**Comment by durden** [comment]
Yea I tend to write all my text in vim with lines wrapped at 80 characters so I run into that also.  On a sidenote, if you're a vim user this [plugin for writing](https://github.com/reedes/vim-pencil) is something I've been playing with for better switching between code/prose writing and soft/hard line breaks.

**Pull request merged**
