### PR TITLE
began intro draft

### PR DESCRIPTION
**Pull request by brown2rl**
working on drafting the body and conclusion from the info I compiled.

### CODE REVIEW

**Comment by durden** [comment]
Looks like a great start!  I'll merge this soon and make the necessary changes to make it visible on the [hack.guides()](http://pluralsight.com/guides) site for potential community editors.

In the meantime, you can see documentation on our [publish workflow](http://hacker-guides-cms.readthedocs.org/en/latest/publish_workflow.html) as well as the reasoning behind our [content repository layout](http://hacker-guides-cms.readthedocs.org/en/latest/github_repo_layout.html).  Essentially we're trying to 'standardize' the layout of guides in the repository so we can support displaying your guide easily on github.com and the [hack.guides()](http://pluralsight.com/guides) site.

Here are the changes I need to make so this is visible on [hack.guides()](http://pluralsight.com/guides)  for future reference.  **Sorry, this should be better documented**. We're still trying to work out the pull request workflow as most our focus has been on the [hack.guides()](http://pluralsight.com/guides) workflow up until now.

First, you'll want to update your fork with the recent `master` after I merged your previous pull request so that changes merge cleanly in the future.

### Small changes to fit hack.guides() structure
1. The folder name for your guide must be based off the title.
   - I've created a folder for your first guide [here](https://github.com/pluralsight/guides/tree/master/draft/front-end-javascript/polymer-user-interfaces-for-the-next-evolution-of-the-web).
2. We ignore nested directories in the guide directory itself.  So, the only files we use are `article.md` and `details.json`.  I'll move the text from your `intro/article.md` into the 'main' `article.md` file.
3. Images will typically be uploaded into the main `images` folder when done via the hack.guides() website.
   - I haven't thought through this completely, but I don't see an immediate problem with your image staying in the article folder itself.  This actually makes more sense, but we typically serve up static files on the `/static` URL so your image will be served up slightly differently.
   - The reason we put all images in a single directory is because when uploaded via our hack.guides() site users might be uploading an image before ever saving a guide.  So, there's no directory to save it in yet.  Also, putting it in a single directory makes it easier to create the correct path to serve up the image for the guide, since there is always one path.
   - I can move the image file if it's necessary, but it might be OK.

### Suggestions welcome

Also, feel free to suggest any improvements to this pull request workflow.  Again, we're still trying to streamline the workflow on github.com.  I'd prefer to let you develop the guide in whatever structure you want when using only pull requests.  However, that makes it difficult for us to properly display your guide on the associated hack.guides() site, create proper URLs to fit the overall site structure, etc.  So, these minor tweaks to directories, etc. are in the interest of making your guide visible to any community editors who only use the hack.guides() interface as well as those who prefer github.com.

### Future improvements

I think the best approach is to have a small API for [hack.guides()](http://pluralsight.com/guides) so people can 'upload'  guide there and all this directory layout stuff is transparent.  This way, authors can write their guides in their own editor, folder layout, etc. and then just 'push' it to us where we'll deal with the details.  This is just an idea I'm bouncing around so there are no firm plans yet. Would something like this be appealing for you?

**The important part is we make your guide visible on github.com and [hack.guides()](http://pluralsight.com/guides) because that will give you the most exposure and potential editing help.**

**Comment by durden** [comment]
@brown2rl Looks like you're still making steady progress.  Would you prefer me to merge this now and make the changes to be visible on the hack.guides() site, or do you want to continue working with your existing directory structure via github.com?  I didn't want to merge this and then move around your content and cause to conflicts if you tried to pull from master later.

**Comment by brown2rl** [comment]
Luke,

Just read the previous comment.  Let's wait on the merge for now until I'm able to change the directory structure per the protocol.

Some quick thoughts include how we are to link articles together within the same tutorial and automating the submission process to ensure consistency between sites.

Thanks!

**Comment by durden** [comment]
@brown2rl Sounds like a good plan.  Let me know when you're ready to roll this in.  Also, yes we definitely need a better process for creating the directory structure outside of the hack.guides() UI.  It's definitely on the road map just now sure how soon I'll be able to get to it.  Thanks again for the suggestions and guide series!

**Comment by brown2rl** [comment]
@durden I updated the personal fork to match the updated PS master branch.  I've also added links to topic/series headers for an SPA-style.

**Comment by durden** [comment]
Thanks! I cleaned up the branches metadata and had to move the image into `/images` so it could be served from github.  You should be able to see this guide on [your hack.guides() profile page](http://tutorials.pluralsight.com/author/brown2rl) now!

**Pull request merged**
