### PR TITLE
Updates to "Building a CRUD interface with React and Ruby on Rails"

### PR DESCRIPTION
**Pull request by durden**

### CODE REVIEW

**Comment by durden** [comment]
Thanks @caike!  The diff looks big because of some line-endings issues with github.  However, you can see a better diff [with this link](https://github.com/pluralsight/guides/commit/077e5c90882a48655a681d71ecb3f61d66a69696?short_path=fcb182d#diff-fcb182df83a5f72cec9df58fefda6c33).  You can also see the 'real' changes locally if you checkout the repo and run the following command:

```
git diff -b 077e5c90882a48655a681d71ecb3f61d66a69696..5293ead75ae577dce55cff541c3226fc44e6f7ad
```

Any thoughts on these suggestions @Kaizeras ?

**Comment by durden** [comment]
I'm not a React developer, but I'm curious about the benefits of subclassing from from `React.Component`.  Any insight on that @caike?

**Comment by hggeorgiev** [comment]
This is the ES6  style syntax for React. It's a matter of preference whether it can be used or not. ES6 is awesome nonetheless.

**Comment by durden** [comment]
Thanks for the information @Kaizeras!  I'll go ahead and close this.

**Comment by caike** [comment]
First of all, thanks for writing this article! 👍  Last I heard from the React team, the ES6 class-style component is the one that's currently being recommended by them, although a lot of the official docs still reference `createClass` ¯_(ツ)_/¯ I realize there's still some examples pending on this article.. I hit save not knowing whether or not it would automatically create a new PR. I will get back to it as soon as I have some time 🙏

**Comment by durden** [comment]
Thanks for the reply @caike.  We're working on improving the 'edit this guide' workflow so authors have a better understanding of what happens.  Right now we just save your edits in a new branch and are manually going through them, creating PRs, etc.  We've been experimenting with several things and want to do things manually for a while until we figure out best workflow on the API side.

**Pull request closed without merging**
